version: '3.6'
services:
  mongo:
    image: mongo:4.2.6-bionic
    ports:
      - "27017:27017"
  backend:
    build: ./backend
    image: backend:latest
    ports:
      - "4000:4000"
    links:
      - mongo
  frontend:
    build: ./frontend
    image: frontend:latest
    ports:
      - "3000:3000"
    links:
      - backend